#!/usr/bin/with-contenv sh

COUNTER=0

setVar(){

    NAME="SITE_"$COUNTER"_"$1
    DATA=$(eval 'echo $'$NAME)
    if [ -z "$DATA" ];
    then 
        echo "\t\t> "$1"\t\t"$2"\t\t(Default)"
        DATA=$2
    else
        echo "\t\t> "$1"\t\t"$DATA
    fi
    sed -i "s,<$1>,$DATA,g" $FILE
}


isSiteEnabled(){
    NAME="SITE_"$COUNTER"_ENABLE"
    ENABLE=$(eval 'echo $'$NAME)
    if [ -z "$ENABLE" ];
    then 
        return 1
    fi


    NAME="SITE_"$COUNTER"_DOMAIN"
    DOMAIN=$(eval 'echo $'$NAME)
    if [ -z "$DOMAIN" ];
    then 
        DOMAIN="_"
    fi
    
    NAME="SITE_"$COUNTER"_CERTBOT"
    CERTBOT=$(eval 'echo $'$NAME)
    if [ -z "$CERTBOT" ];
    then 
        CERTBOT="NO"
    fi
    FILE="/etc/nginx/conf.d/$DOMAIN.conf"

    return 0
}


install(){
    echo "> Install Template"
    cp /etc/nginx/template/proxypass.conf $FILE
      
}


certbot(){
    echo "> Install Certbot"
    if [ "x$CERTBOT" = "xYES" ];
    then
        sed -i "s,<CERTBOT>,,g" $FILE
        echo "# $DOMAIN" >> /etc/periodic/weekly/01-certbot.sh
        echo "echo 2 | certbot certonly --webroot -w /var/www/certbot/$DOMAIN --email ${CERTBOT_EMAIL} -d $DOMAIN" >> /etc/periodic/weekly/01-certbot.sh
        echo "echo 2 | certbot --nginx -d $DOMAIN" >> /etc/periodic/weekly/01-certbot.sh
    else
        grep -v "<CERTBOT>" $FILE > $FILE.temp
        mv $FILE.temp $FILE
    fi
    
}

next(){
    echo "> Get Next Site"
    COUNTER=$(($COUNTER + 1))
}

echo "============= START ==============="
rm /etc/nginx/conf.d/* 
echo "#!/usr/bin/with-contenv sh" > /etc/periodic/weekly/01-certbot.sh
chmod +x /etc/periodic/weekly/01-certbot.sh
chown nginx:nginx /var/www/certbot/ -R
while [ 1 -eq 1 ];
do    
    if ! isSiteEnabled;
    then
        break
    fi
    install;
    setVar "DOMAIN" "_"
    setVar "DOMAIN_PATH" "/"
    setVar "HOST" "localhost"
    setVar "HOST_PATH" "/"
    setVar "HOST_PROTO" "http"
    setVar "HOST_PORT" "80"
    certbot;
    next; 
done
echo "============= DONE ==============="
