#!/usr/bin/with-contenv sh

COUNTER=0

set_var(){

    NAME="SITE_"$COUNTER"_"$1
    DATA=$(eval 'echo $'$NAME)
    if [ -z "$DATA" ];
    then 
        echo "    > "$1"    "$2"    (Default)"
        DATA=$2
    else
        echo "    > "$1"    "$DATA
    fi
    sed -i "s,<$1>,$DATA,g" $FILE
}

do_restart_nginx(){
	killall -9 nginx
}

is_site_enabled(){
    NAME="SITE_"$COUNTER"_ENABLE"
    ENABLE=$(eval 'echo $'$NAME)
    if [ -z "$ENABLE" ];
    then 
        return 1
    fi


    NAME="SITE_"$COUNTER"_DOMAIN"
    DOMAIN=$(eval 'echo $'$NAME)
    if [ -z "$DOMAIN" ];
    then 
        DOMAIN="_"
    fi
    
    NAME="SITE_"$COUNTER"_CERTBOT"
    CERTBOT=$(eval 'echo $'$NAME)
    if [ -z "$CERTBOT" ];
    then 
        CERTBOT="NO"
    fi
    FILE="/etc/nginx/conf.d/$DOMAIN.conf"
    TEMPFILE="/tmp/$DOMAIN.conf"

    return 0
}


do_install(){
    echo "> do_install Template"
    cp /etc/nginx/template/proxypass.conf $FILE      
}


do_certbot(){
    echo "> do_install Certbot"
    if [  "$CERTBOT" == "YES" ]
    then
        mkdir /var/www/certbot/$DOMAIN -p    
        if  [ -f /etc/letsencrypt/live/$DOMAIN/fullchain.pem ]
        then
            now=$( date +%s )
            days_ago=$(( $now - 604800 ))
            file_time=$(date -r "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" +%s)
            if [ $file_time -le $days_ago ]
            then
                echo "2" | certbot certonly --webroot -w /var/www/certbot/$DOMAIN --email $CERTBOT_EMAIL -d $DOMAIN
            fi
        else

            mv $FILE $TEMPFILE
            grep -v "#CERTBOT" $TEMPFILE > $FILE
            do_restart_nginx;
            chown nginx:nginx /var/www/certbot/$DOMAIN -R

            if [ -f /etc/letsencrypt/firsttime ]
            then 
                echo "2" | certbot certonly --webroot -w /var/www/certbot/$DOMAIN --email $CERTBOT_EMAIL -d $DOMAIN
            	RET=$?
            else
                echo -e 'A\nY\n' | certbot certonly --webroot -w /var/www/certbot/$DOMAIN --email $CERTBOT_EMAIL -d $DOMAIN
            	RET=$?
                echo "1" > /etc/letsencrypt/firsttime
            fi

            if [ "$RET" == "0" ]
	        then 
		        mv $TEMPFILE $FILE
		        do_restart_nginx;
        	fi    
        fi
	else
        grep -v "#CERTBOT" $FILE > $TEMPFILE
        mv $FILE.temp $FILE
    fi
}

next(){
    echo "> Get Next Site"
    COUNTER=$(($COUNTER + 1))
}

echo "============= START ==============="

chown nginx:nginx /var/www/certbot/ -R
while [ 1 -eq 1 ];
do    
    if ! is_site_enabled;
    then
        break
    fi
    echo $FILE
    if [ -f "$FILE" ]
    then
 	    echo "$FILE found."
    else
	    echo "file not found"
        do_install;
        set_var "DOMAIN" "_"
        set_var "DOMAIN_PATH" "/"
        set_var "HOST" "localhost"
        set_var "HOST_PATH" "/"
        set_var "HOST_PROTO" "http"
        set_var "HOST_PORT" "80"
    fi
    do_certbot;
    next; 
done
echo "============= DONE ==============="
killall -9 nginx
